import type { Locale } from "@/lib/i18n";
import type { TaskStatus } from "@/types/content";

const copy = {
  vi: {
    workspace: "Quản trị lab",
    overview: "Tổng quan",
    teams: "Walls",
    tasks: "Tasks",
    progress: "Tiến độ",
    members: "Thành viên",
    accounts: "Tài khoản",
    publicContent: "Nội dung công khai",
    publications: "Công bố",
    projects: "Dự án",
    applications: "Đơn liên hệ",
    settings: "Cài đặt",
    signOut: "Đăng xuất",
    signIn: "Đăng nhập",
    signInTitle: "Đăng nhập quản trị",
    signInDescription: "Dùng tài khoản Firebase đã được cấp quyền để quản lý Blockchainist.",
    email: "Email",
    password: "Mật khẩu",
    accessDenied: "Tài khoản này không có quyền quản trị Blockchainist.",
    invalidCredentials: "Email hoặc mật khẩu không chính xác.",
    loginFailed: "Không thể đăng nhập. Kiểm tra cấu hình Firebase và kết nối mạng.",
    loading: "Đang tải...",
    refresh: "Làm mới",
    create: "Tạo mới",
    save: "Lưu",
    cancel: "Hủy",
    edit: "Chỉnh sửa",
    delete: "Xóa",
    close: "Đóng",
    confirmDelete: "Xóa mục này?",
    syncOrcid: "Đồng bộ ORCID",
    syncingOrcid: "Đang đồng bộ ORCID",
    dataUpdated: "Dữ liệu đã được cập nhật.",
    overviewTitle: "Theo dõi hoạt động lab",
    overviewDescription: "Nắm tiến độ, các task cần xử lý và cập nhật mới nhất.",
    activeTeams: "Team đang hoạt động",
    activeMembers: "Thành viên active",
    openTasks: "Task chưa hoàn thành",
    blockedTasks: "Task bị chặn",
    overdueTasks: "Task quá hạn",
    pendingApplications: "Đơn chờ xử lý",
    attentionTasks: "Task cần chú ý",
    attentionDescription: "Task bị chặn hoặc đã quá deadline.",
    recentProgress: "Cập nhật tiến độ mới",
    staleTeams: "Team chưa cập nhật 14 ngày",
    staleDescription: "Không có cập nhật tiến độ trong 14 ngày gần đây.",
    noAttentionTasks: "Không có task nào cần xử lý ngay.",
    noProgress: "Chưa có cập nhật tiến độ.",
    noStaleTeams: "Tất cả team đang cập nhật đúng nhịp.",
    due: "Hạn",
    noDeadline: "Chưa có hạn",
    noTeam: "Không thuộc team",
    unknownMember: "Thành viên chưa xác định",
    unknownTeam: "Team chưa xác định",
    teamTitle: "Quản lý Wall",
    teamDescription: "Phân thành viên và quản lý từng Wall làm việc.",
    taskTitle: "Quản lý công việc",
    taskDescription: "Giao việc, hạn hoàn thành và người phụ trách theo từng Wall.",
    progressTitle: "Tiến độ toàn lab",
    progressDescription: "Xem các cập nhật do thành viên gửi, theo team và task.",
    name: "Tên",
    slug: "Slug",
    description: "Mô tả",
    active: "Đang hoạt động",
    archived: "Đã lưu trữ",
    team: "Wall",
    status: "Trạng thái",
    deadline: "Hạn hoàn thành",
    updatedAt: "Cập nhật",
    assignees: "Người thực hiện",
    memberList: "Thành viên",
    researchFocus: "Hướng nghiên cứu",
    taskName: "Tên task",
    expectedOutcome: "Kết quả mong đợi",
    noTeams: "Chưa có Wall nào.",
    noTasks: "Chưa có task nào.",
    noMembers: "Chưa có thành viên phù hợp.",
    newTeam: "Tạo Wall",
    editTeam: "Chỉnh sửa Wall",
    newTask: "Tạo task",
    editTask: "Chỉnh sửa task",
    selectTeam: "Chọn Wall",
    wallNeedsMember: "Wall cần ít nhất một thành viên phụ trách.",
    taskNeedsAssignee: "Task cần ít nhất một người phụ trách.",
    noActiveMembersWarning: "Wall này hiện không có thành viên hoạt động nào phụ trách (tài khoản thành viên trước đó có thể đã bị vô hiệu hóa). Vui lòng chọn ít nhất 1 thành viên hoạt động thay thế.",
    noActiveAssigneesWarning: "Task này hiện không có người phụ trách hoạt động nào (tài khoản trước đó có thể đã bị vô hiệu hóa). Vui lòng chọn ít nhất 1 người phụ trách thay thế.",
    noActiveMembersInWall: "Wall này chưa có thành viên hoạt động nào để giao việc. Vui lòng thêm thành viên vào Wall trước.",
    deactivated: "Đã vô hiệu hóa",
    needsMemberAssignment: "Cần gán thành viên",
    unassigned: "Chưa có người phụ trách",
    records: "bản ghi",
    recordsTitle: "Dữ liệu quản lý",
    tablePrimary: "Nội dung",
    tableSecondary: "Thông tin",
    tableState: "Trạng thái",
    actions: "Thao tác",
    noRecords: "Chưa có dữ liệu.",
    newRecord: "Tạo mới",
    homepageSettings: "Cài đặt trang chủ",
    settingsSaved: "Đã lưu cài đặt.",
    accountsTitle: "Tài khoản lab",
    createAccount: "Cấp tài khoản thành viên",
    accountDescription: "Thành viên nhận email đặt lại mật khẩu và tự hoàn thiện hồ sơ sau khi đăng nhập.",
    linkedProfile: "Hồ sơ đã liên kết",
    newProfile: "Tạo hồ sơ mới bên dưới",
    profileName: "Tên hồ sơ mới",
    profileSlug: "Slug hồ sơ mới",
    researchRole: "Vai trò nghiên cứu",
    accountCreated: "Đã tạo tài khoản.",
    invitationSent: "Đã tạo tài khoản và gửi email mời.",
    invitationFailed: "Tài khoản đã tạo nhưng không thể gửi email đặt lại mật khẩu.",
    accountUpdated: "Đã cập nhật tài khoản thành công.",
    accountDeactivated: "Đã vô hiệu hóa tài khoản thành công.",
    accountActivated: "Đã kích hoạt tài khoản thành công.",
    passwordResetSent: "Đã gửi email đặt lại mật khẩu.",
    teamSaved: "Đã lưu thông tin Wall thành công.",
    teamCreated: "Đã tạo Wall mới thành công.",
    teamDeleted: "Đã lưu trữ Wall thành công.",
    taskSaved: "Đã lưu thông tin task thành công.",
    taskCreated: "Đã tạo task mới thành công.",
    taskDeleted: "Đã xóa task thành công.",
    provisionedAccounts: "tài khoản đã cấp",
    noAccounts: "Chưa có tài khoản thành viên.",
    resetPassword: "Đặt lại mật khẩu",
    role: "Vai trò",
    profile: "Hồ sơ",
    notLinked: "Chưa liên kết",
    taskStatuses: {
      in_progress: "Đang làm",
      blocked: "Đang bị chặn",
      completed: "Hoàn thành"
    }
  },
  en: {
    workspace: "Lab administration",
    overview: "Overview",
    teams: "Walls",
    tasks: "Tasks",
    progress: "Progress",
    members: "Members",
    accounts: "Accounts",
    publicContent: "Public content",
    publications: "Publications",
    projects: "Projects",
    applications: "Applications",
    settings: "Settings",
    signOut: "Sign out",
    signIn: "Sign in",
    signInTitle: "Admin sign in",
    signInDescription: "Use a Firebase account with permission to manage Blockchainist.",
    email: "Email",
    password: "Password",
    accessDenied: "This account is not authorized to administer Blockchainist.",
    invalidCredentials: "Email or password is incorrect.",
    loginFailed: "Unable to sign in. Check the Firebase configuration and network connection.",
    loading: "Loading...",
    refresh: "Refresh",
    create: "Create",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    close: "Close",
    confirmDelete: "Delete this item?",
    syncOrcid: "Sync ORCID",
    syncingOrcid: "Syncing ORCID",
    dataUpdated: "Data has been updated.",
    overviewTitle: "Lab operations overview",
    overviewDescription: "Track progress, items needing attention, and the latest updates.",
    activeTeams: "Active teams",
    activeMembers: "Active members",
    openTasks: "Open tasks",
    blockedTasks: "Blocked tasks",
    overdueTasks: "Overdue tasks",
    pendingApplications: "Pending applications",
    attentionTasks: "Tasks needing attention",
    attentionDescription: "Blocked tasks or tasks past their deadline.",
    recentProgress: "Recent progress",
    staleTeams: "Teams without updates for 14 days",
    staleDescription: "No progress update in the last 14 days.",
    noAttentionTasks: "No tasks need immediate attention.",
    noProgress: "No progress updates yet.",
    noStaleTeams: "Every team is updating on schedule.",
    due: "Due",
    noDeadline: "No deadline",
    noTeam: "No team",
    unknownMember: "Unknown member",
    unknownTeam: "Unknown team",
    teamTitle: "Manage walls",
    teamDescription: "Assign members and manage each working wall.",
    taskTitle: "Manage tasks",
    taskDescription: "Assign tasks, deadlines, and responsibilities for each wall.",
    progressTitle: "Lab-wide progress",
    progressDescription: "Review updates submitted by members, teams, and tasks.",
    name: "Name",
    slug: "Slug",
    description: "Description",
    active: "Active",
    archived: "Archived",
    team: "Wall",
    status: "Status",
    deadline: "Deadline",
    updatedAt: "Updated",
    assignees: "Assignees",
    memberList: "Members",
    researchFocus: "Research focus",
    taskName: "Task title",
    expectedOutcome: "Expected outcome",
    noTeams: "No walls yet.",
    noTasks: "No tasks yet.",
    noMembers: "No eligible members.",
    newTeam: "New wall",
    editTeam: "Edit wall",
    newTask: "New task",
    editTask: "Edit task",
    selectTeam: "Select wall",
    wallNeedsMember: "A wall needs at least one member.",
    taskNeedsAssignee: "A task needs at least one assignee.",
    noActiveMembersWarning: "This wall currently has no active members (previously assigned accounts may have been deactivated). Please select at least one active member.",
    noActiveAssigneesWarning: "This task currently has no active assignees (previously assigned accounts may have been deactivated). Please select at least one active assignee.",
    noActiveMembersInWall: "This wall has no active members to assign. Please add members to the wall first.",
    deactivated: "Deactivated",
    needsMemberAssignment: "Needs member assignment",
    unassigned: "Unassigned",
    records: "records",
    recordsTitle: "Managed data",
    tablePrimary: "Primary",
    tableSecondary: "Secondary",
    tableState: "State",
    actions: "Actions",
    noRecords: "No records yet.",
    newRecord: "New record",
    homepageSettings: "Homepage settings",
    settingsSaved: "Settings saved.",
    accountsTitle: "Lab accounts",
    createAccount: "Create member account",
    accountDescription: "The member receives a password-reset invitation and completes their profile after signing in.",
    linkedProfile: "Existing profile",
    newProfile: "Create a new profile below",
    profileName: "New profile name",
    profileSlug: "New profile slug",
    researchRole: "Research role",
    accountCreated: "Account created.",
    invitationSent: "Account created and invitation sent.",
    invitationFailed: "Account created, but the password-reset email could not be sent.",
    accountUpdated: "Account updated successfully.",
    accountDeactivated: "Account deactivated successfully.",
    accountActivated: "Account activated successfully.",
    passwordResetSent: "Password reset email sent.",
    teamSaved: "Wall saved successfully.",
    teamCreated: "Wall created successfully.",
    teamDeleted: "Wall archived successfully.",
    taskSaved: "Task saved successfully.",
    taskCreated: "Task created successfully.",
    taskDeleted: "Task deleted successfully.",
    provisionedAccounts: "provisioned accounts",
    noAccounts: "No member accounts yet.",
    resetPassword: "Reset password",
    role: "Role",
    profile: "Profile",
    notLinked: "Not linked",
    taskStatuses: {
      in_progress: "In progress",
      blocked: "Blocked",
      completed: "Completed"
    }
  }
} as const;

export function getAdminCopy(locale: Locale) {
  return copy[locale];
}

export function taskStatusLabel(locale: Locale, status: TaskStatus) {
  return copy[locale].taskStatuses[status];
}
